version: '3.8'

services:
  app:
    image: ghcr.io/matteygg/stasis-web:latest
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - './public:/src/public'

networks:
  app-network: